# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'route.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0broute.proto\x12\x04loop\"\x16\n\x07Request\x12\x0b\n\x03rid\x18\x01 \x01(\t\"\x19\n\x08Response\x12\r\n\x05rspid\x18\x02 \x01(\t26\n\x0cRouteService\x12&\n\x05Hello\x12\r.loop.Request\x1a\x0e.loop.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=21
  _globals['_REQUEST']._serialized_end=43
  _globals['_RESPONSE']._serialized_start=45
  _globals['_RESPONSE']._serialized_end=70
  _globals['_ROUTESERVICE']._serialized_start=72
  _globals['_ROUTESERVICE']._serialized_end=126
# @@protoc_insertion_point(module_scope)
